baseURL = "https://go-binaria.netlify.app"
languageCode = "es-la"
title = "BinariaOS App"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "ubuntu"

    [Params.Tree]
    use = true
    files = [
        ["e-Commerce", "https://shop.binariaos.com.py"],
        ["WordPress", "https://sites.binariaos.com.py"],
        ["MS-DOS", "https://binariaos.com.py/1980"],
        ["Dev in Go", "/works/go.md"]
    ]
